[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
reclaim = "rEcLDWaVLaymz82eGr6cutosPxE6SEzw6q4pbtLuyqf"
airdrop = "ArdPv6gtzY8HQuxzVQbZ8GHMRUatySoUv8jZH4vFj4Tm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sundeepcharanramkumar/.config/solana/id.json"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/index.ts"
