[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
reclaim = "HPHX51Lt497k57RoegWnzhg2Spvaui4kc93dDFwhpbwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sundeepcharanramkumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
